using UnityEngine;
using TMPro;

namespace TrueDetective.UI
{
    /// <summary>
    /// Every colour, size and font in one place. A detective-desk palette: charcoal
    /// room, warm paper for anything the player reads, one amber accent used only for
    /// what is actionable, and a single red reserved for a proven contradiction.
    ///
    /// Fonts are built at runtime from the TTFs in Resources/Fonts via TMP's dynamic
    /// atlas, so no font asset has to be generated by hand and any Arabic glyph the
    /// text needs is rasterised on demand.
    /// </summary>
    public static class Theme
    {
        // ---- palette ----
        public static readonly Color Ink        = new Color32(0x14, 0x16, 0x1A, 0xFF); // deepest bg
        public static readonly Color Room       = new Color32(0x1D, 0x21, 0x28, 0xFF); // panel bg
        public static readonly Color RoomLight  = new Color32(0x2A, 0x30, 0x3A, 0xFF); // raised panel
        public static readonly Color Paper      = new Color32(0xEC, 0xE3, 0xD2, 0xFF); // documents
        public static readonly Color PaperEdge  = new Color32(0xCB, 0xBE, 0xA6, 0xFF);
        public static readonly Color TextOnDark = new Color32(0xE8, 0xE6, 0xE1, 0xFF);
        public static readonly Color TextMuted  = new Color32(0x98, 0xA0, 0xAC, 0xFF);
        public static readonly Color TextOnPaper= new Color32(0x1E, 0x1B, 0x16, 0xFF);
        public static readonly Color Amber      = new Color32(0xE0, 0xA1, 0x3E, 0xFF); // actionable
        public static readonly Color AmberDim   = new Color32(0x7A, 0x58, 0x22, 0xFF);
        public static readonly Color Alert      = new Color32(0xC9, 0x4B, 0x3F, 0xFF); // contradiction
        public static readonly Color Verified   = new Color32(0x5A, 0x9E, 0x6F, 0xFF); // proven
        public static readonly Color Shade      = new Color32(0x00, 0x00, 0x00, 0xB4); // modal veil

        // ---- type scale, in reference pixels against a 1080x1920 canvas ----
        public const float SizeDisplay = 74f;   // newspaper headline
        public const float SizeTitle   = 52f;
        public const float SizeHeading = 42f;
        public const float SizeBody    = 36f;
        public const float SizeSmall   = 30f;
        public const float SizeTiny    = 26f;

        /// <summary>Arabic needs far more leading than Latin or it reads as a solid block.</summary>
        public const float LineSpacing = 28f;   // TMP line spacing, percent-of-em units

        public const float Gutter      = 40f;   // side margin
        public const float TouchMin    = 110f;  // minimum tappable height

        private static TMP_FontAsset _ui;
        private static TMP_FontAsset _serif;
        private static TMP_FontAsset _serifBold;

        /// <summary>
        /// IBM Plex Sans Arabic — screen font for everything the player interacts with.
        ///
        /// The choice is not cosmetic. ArabicText.Fix emits codepoints from the Arabic
        /// Presentation Forms-B block (U+FE70-FEFF), and many otherwise excellent Arabic
        /// fonts - Cairo and Tajawal among them - cover only about 62% of it, because
        /// they expect OpenType shaping to do the joining instead. Those fonts render
        /// this game as rows of empty boxes. Plex and Amiri both cover ~97%, which is
        /// every assigned codepoint in the block.
        ///
        /// Any replacement font must be checked against that range before being used.
        /// </summary>
        public static TMP_FontAsset UIFont
        {
            get { if (_ui == null) _ui = Load("Fonts/IBMPlexSansArabic-Regular"); return _ui; }
        }

        /// <summary>Amiri — naskh, used for the newspaper and case documents.</summary>
        public static TMP_FontAsset SerifFont
        {
            get { if (_serif == null) _serif = Load("Fonts/Amiri-Regular"); return _serif; }
        }

        public static TMP_FontAsset SerifBoldFont
        {
            get { if (_serifBold == null) _serifBold = Load("Fonts/Amiri-Bold"); return _serifBold; }
        }

        private static TMP_FontAsset Load(string resourcePath)
        {
            // a hand-made font asset wins if one was ever generated for this font
            var preMade = Resources.Load<TMP_FontAsset>(resourcePath + " SDF");
            if (preMade != null) return preMade;

            var ttf = Resources.Load<Font>(resourcePath);
            if (ttf == null)
            {
                Debug.LogError("[Theme] font not found at Resources/" + resourcePath +
                               " - falling back to the TMP default, Arabic will not render.");
                return SafeDefault();
            }

            // TMP_Settings lives in an asset that ships as a separate .unitypackage. Without
            // it, CreateFontAsset throws a NullReferenceException from inside TMP that says
            // nothing about the real cause, so check first and name the fix.
            if (TMP_Settings.instance == null)
            {
                Debug.LogError(
                    "[Theme] TextMeshPro essential resources are missing, so no font can be built.\n" +
                    "Run: True Detective > Import TextMeshPro Resources\n" +
                    "(or Window > TextMeshPro > Import TMP Essential Resources), then press Play again.");
                return null;
            }

            TMP_FontAsset asset;
            try
            {
                asset = TMP_FontAsset.CreateFontAsset(ttf);
            }
            catch (System.Exception e)
            {
                Debug.LogError("[Theme] CreateFontAsset threw for " + resourcePath + ": " + e.Message);
                return SafeDefault();
            }

            if (asset == null)
            {
                Debug.LogError("[Theme] CreateFontAsset returned null for " + resourcePath);
                return SafeDefault();
            }

            asset.name = resourcePath + " (runtime)";
            // Dynamic keeps rasterising glyphs as new text appears, which is exactly what
            // Arabic presentation forms need - they are never all known up front.
            asset.atlasPopulationMode = AtlasPopulationMode.Dynamic;
            return asset;
        }

        /// <summary>TMP's own default, or null if TMP itself is not set up yet.</summary>
        private static TMP_FontAsset SafeDefault()
        {
            return TMP_Settings.instance != null ? TMP_Settings.defaultFontAsset : null;
        }

        /// <summary>Drops cached font assets. Only needed if fonts are swapped at runtime.</summary>
        public static void ClearFontCache()
        {
            _ui = null; _serif = null; _serifBold = null;
        }
    }
}
